---
- name: Ensure directory structure exists
  file:
    path: '{{ kube_dir }}/{{ item.path }}'
    state: directory
  with_filetree: '{{ kubernetes_source }}'
  when: item.state == 'directory'

- name: Ensure files are populated from templates
  template:
    src: '{{ item.src }}'
    dest: '{{ kube_dir }}/{{ item.path }}'
  with_filetree: '{{ kubernetes_source }}'
  when: item.state == 'file'

- name: Add nginx config
  include_role:
    name: roles/add_nginx_config