# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-31 03:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_breed_dog'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='dogbreed',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.Breed'),
        ),
    ]
