# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-12 05:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_dog_dogbreed'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=300)),
                ('platform', models.CharField(choices=[('PS4', 'PS4'), ('XB1', 'XB1'), ('SWTCH', 'SWTCH'), ('PC', 'PC')], max_length=100)),
                ('developer', models.CharField(max_length=300)),
                ('publisher', models.CharField(max_length=300)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
            ],
        ),
        migrations.RemoveField(
            model_name='dog',
            name='dogbreed',
        ),
        migrations.DeleteModel(
            name='Breed',
        ),
        migrations.DeleteModel(
            name='Dog',
        ),
    ]
