# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-15 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201212_0532'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogame',
            name='owned',
            field=models.CharField(choices=[('Owned', 'Owned'), ('Wish', 'Wish')], default='some_string', max_length=300),
        ),
    ]
