# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-15 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_videogame_owned'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogame',
            name='status',
            field=models.CharField(choices=[('Unplayed', 'Unplayed'), ('In Progress', 'In Progress'), ('Main Story Completed', 'Main Story Completed'), ('100% Completed', '100% Completed')], default='some_string', max_length=100),
        ),
    ]
