# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-15 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_videogame_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogame',
            name='upload',
            field=models.ImageField(upload_to=b''),
        ),
    ]
