# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-15 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20201215_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogame',
            name='upload',
            field=models.ImageField(upload_to='BoxArt'),
        ),
    ]
