# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-17 04:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20201215_0431'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnedStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='videogame',
            name='status',
        ),
        migrations.AlterField(
            model_name='videogame',
            name='owned',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.OwnedStatus'),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='platform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Platform'),
        ),
        migrations.AddField(
            model_name='videogame',
            name='progress',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ProgressStatus'),
        ),
    ]
