# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-17 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20201217_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogame',
            name='upload',
            field=models.ImageField(upload_to='./static/images/'),
        ),
    ]
