# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-17 07:50
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20201217_0505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videogame',
            name='id',
        ),
        migrations.AddField(
            model_name='videogame',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
