# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-17 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20201217_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogame',
            name='upload',
            field=models.ImageField(max_length=500, null=True, upload_to='./static/images/'),
        ),
    ]
