# my-config.yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  tag: latest
  revision: {{istiod_revision}}
  meshConfig:
    accessLogFile: "{{kube_dir}}/logs/istio.log"
    enableTracing: true
