---
- name: "Get all objects from {{aws_artifacts_bucket}}"
  aws_s3:
    mode: list
    access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
    bucket: "{{aws_artifacts_bucket}}"
  register: aws_bucket_objects

- name: "Clean up folders"
  file:
    path: "{{item}}"
    state: absent
  loop:
    - "{{tmp_location}}"
    - "{{artifacts_dir}}"

- name: "Create folders"
  file:
    path: "{{item}}"
    state: directory
  loop:
    - "{{tmp_location}}"
    - "{{artifacts_dir}}"

- name: Download artifacts
  aws_s3:
    access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
    mode: get
    bucket: "{{aws_artifacts_bucket}}"
    object: "{{item}}"
    dest: "{{tmp_location}}/{{item}}"
  loop:
    "{{aws_bucket_objects.s3_keys}}"

- name: "Create folders"
  file:
    # example file.tar.gz -> file
    path: "{{artifacts_dir}}/{{item.split('.') | first}}"
    state: directory
  loop:
    "{{aws_bucket_objects.s3_keys}}"

- name: Extract to staging dir
  unarchive:
      src: "{{tmp_location}}/{{item}}"
      dest: "{{artifacts_dir}}/{{item.split('.') | first}}"
  loop: "{{aws_bucket_objects.s3_keys}}"
  
