database:
  type: postgres
  host: {{rest_db_service_name}}
  port: {{rest_db_service_port}}
  username: {{db_user}}
  password: {{db_password}}
  database: {{rest_db_name}}

microservices:
  userservice:
    port: {{ms_user_service_port}}
    host: {{ms_user_service_name}}