apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gamex-gateway
  namespace: {{kube_namespace}}
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*" # this will have to change for prod
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "*"
    tls:
      mode: SIMPLE
      credentialName: {{cert_secret_name}}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: gamex-virutal-service
  namespace: {{kube_namespace}}
spec:
  hosts:
  - "*"
  gateways:
  - gamex-gateway
  http:
  - match:
    - uri:
        prefix: /auth/
    route:
    - destination:
        host: {{keycloak_service_name}}
        port:
          number: 8080
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: {{nginx_service_name}}
        port:
          number: 80