kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: local-pvc
  namespace: {{kube_namespace}}
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: my-local-storage
  resources:
    requests:
      storage: 3Gi