kube_namespace: "{{app_name}}"
kube_environment: stage

staging_dir: "{{ansible_env.HOME}}/staging_dir/{{kube_environment}}"
artifacts_dir: "{{staging_dir}}/artifacts"

kube_dir: "{{staging_dir}}/kubernetes"
kube_environment_dir: "{{kube_dir}}/{{kube_environment}}"

kube_local_volume_dir: "{{kube_dir}}/stage/volumes/local"

dummy_pod_yaml_file: "{{kube_dir}}/populate_data/dummy-pod.yaml"
volume_mount_point: /mnt/data

istio_namespace: istio-system
istiod_revision: 1-8-0

cert_manager_namespace: cert-manager



ingress_nginx_host: "localhost"
ingress_nginx_port: 80

server_gateway_service_name: server-gateway-service
server_gateway_service_port: 3000

ms_user_service_name: ms_user-service
ms_user_service_port: 4000

nginx_service_name: nginx-service
nginx_service_port: 80

keycloak_service_name: keycloak-service
keycloak_service_port: 8080

keycloak_exec: "kubectl exec svc/{{keycloak_service_name}} -n {{kube_namespace}} --"