kubernetes_source: ../templates/kubernetes
nginx_mount_path: /var/www
nginx_conf_dir: "{{kube_dir}}/bases/nginx"
www_static_dir: "{{nginx_mount_path}}/frontend/app"


##############################
# cert
##############################
cert_email: "{{vault_cert_email}}"
cert_secret_name: "{{app_name}}-cert"
cert_server: https://acme-staging-v02.api.letsencrypt.org/directory
cert_issuer_name: letsencrypt-staging