version: "3"

volumes:
  postgres-config:
  postgres-data:
  postgres-logs:
  keycloak-datastore:

networks:
  gamex_net:
  keycloak_net:

services:
  ###################################################################
  ## GATEWAY
  ###################################################################
  {{nginx_service_name}}:
    restart: on-failure
    image: redsolid/openresty-oidc
    ports:
      - "80:80"
    volumes:
      - "{{nginx_conf_dir}}/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf"
      - "{{working_frontend_dist_dir}}:{{www_frontend_dir}}"
    networks:
      - gamex_net

  {{server_gateway_service_name}}:
    restart: on-failure
    image: node:14.15.3-alpine3.10
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV={{app_mode}}
    volumes:
      - "{{working_rest_server_dir}}:/home/node/app"
      - "{{server_gateway_dir}}/entrypoint.sh:/entrypoint.sh"
      - "{{server_gateway_dir}}/config.yml:/config.yml"
    ports:
      - "{{server_gateway_service_port}}:{{server_gateway_service_port}}"
    command: sh /entrypoint.sh
    networks:
      - gamex_net

  ##################################################################
  ## KEYCLOAK AUTH
  ##################################################################
  {{keycloak_db_service_name}}:
    image: postgres:13.1-alpine
    restart: on-failure
    volumes:
      - keycloak-datastore:/var/lib/postgresql/data
    ports:
      - "25432:5432"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    networks:
      - keycloak_net

  {{keycloak_service_name}}:
    image: jboss/keycloak:12.0.1
    restart: on-failure
    environment:
      - KEYCLOAK_USER={{keycloak_user}}
      - KEYCLOAK_PASSWORD={{keycloak_password}}
      - DB_VENDOR=postgres
      - DB_USER={{db_user}}
      - DB_PASSWORD={{db_password}}
      - DB_ADDR={{keycloak_db_service_name}}
      - DB_PORT=5432
      - DB_DATABASE=keycloak
      - PROXY_ADDRESS_FORWARDING=true
    ports:
      - "{{keycloak_service_port}}:{{keycloak_service_port}}"
    depends_on:
      - {{keycloak_db_service_name}}
    networks:
      - keycloak_net
      - gamex_net

  ##################################################################
  ## MICROSERVICE STACK
  ##################################################################
  {{ms_user_service_name}}:
    restart: on-failure
    image: node:14.15.3-alpine3.10
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV={{app_mode}}
      - PORT={{ms_user_service_port}}
    volumes:
      - "{{working_rest_server_dir}}:/home/node/app"
      - "{{ms_userservice_dir}}/entrypoint.sh:/entrypoint.sh"
    ports:
      - "{{ms_user_service_port}}:{{ms_user_service_port}}"
    command: sh /entrypoint.sh
    networks:
      - gamex_net

  {{rest_db_service_name}}:
    restart: on-failure
    image: postgres:13.1-alpine
    environment:
      POSTGRES_USER: {{db_user}}
      POSTGRES_PASSWORD: {{db_password}}
      POSTGRES_DB: postgresdb
    volumes:
      - postgres-config:/etc/postgresql
      - postgres-data:/var/lib/postgresql/data
      - postgres-logs:/var/log/postgresql
    networks:
      - gamex_net
