version: "3"

volumes:
  postgres-config:
  postgres-data:
  postgres-logs:
  keycloak-datastore:

networks:
  gamex_net:
  keycloak_net:

services:
  ###################################################################
  ## GATEWAY
  ###################################################################
  openresty:
    build: {{openresty_dir}}
    restart: on-failure
    image: openresty-oidc:latest
    ports:
      - "80:80"
    volumes:
      - "{{nginx_conf_dir}}/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf"
      - "{{working_rest_server_dir}}/testing:{{www_static_dir}}"
    networks:
      - gamex_net

  server_gateway:
    restart: on-failure
    image: node:14.15.3-alpine3.10
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV={{app_mode}}
    volumes:
      - "{{working_rest_server_dir}}:/home/node/app"
      - "{{server_gateway_dir}}/entrypoint.sh:/entrypoint.sh"
      - "{{server_gateway_dir}}/config.yml:/config.yml"
    ports:
      - "3000:3000"
    command: sh /entrypoint.sh
    networks:
      - gamex_net

  ##################################################################
  ## KEYCLOAK AUTH
  ##################################################################
  keycloak-db:
    image: postgres:13.1-alpine
    restart: on-failure
    volumes:
      - keycloak-datastore:/var/lib/postgresql/data
    ports:
      - "25432:5432"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    networks:
      - keycloak_net

  keycloak:
    image: jboss/keycloak:12.0.1
    restart: on-failure
    environment:
      - KEYCLOAK_USER={{keycloak_user}}
      - KEYCLOAK_PASSWORD={{keycloak_password}}
      - DB_VENDOR=postgres
      - DB_USER={{db_user}}
      - DB_PASSWORD={{db_password}}
      - DB_ADDR=keycloak-db
      - DB_PORT=5432
      - DB_DATABASE=keycloak
      - PROXY_ADDRESS_FORWARDING=true
    ports:
      - "8080:8080"
    depends_on:
      - keycloak-db
    networks:
      - keycloak_net
      - gamex_net

  ##################################################################
  ## MICROSERVICE STACK
  ##################################################################
  {{ms_userservice_host}}:
    restart: on-failure
    image: node:14.15.3-alpine3.10
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV={{app_mode}}
      - PORT={{ms_userservice_port}}
    volumes:
      - "{{working_rest_server_dir}}:/home/node/app"
      - "{{ms_userservice_dir}}/entrypoint.sh:/entrypoint.sh"
    ports:
      - "{{ms_userservice_port}}:{{ms_userservice_port}}"
    command: sh /entrypoint.sh
    networks:
      - gamex_net

  rest-db:
    restart: on-failure
    image: postgres:13.1-alpine
    environment:
      POSTGRES_USER: {{db_user}}
      POSTGRES_PASSWORD: {{db_password}}
      POSTGRES_DB: postgresdb
    volumes:
      - postgres-config:/etc/postgresql
      - postgres-data:/var/lib/postgresql/data
      - postgres-logs:/var/log/postgresql
    networks:
      - gamex_net
