apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{cert_secret_name}}
  namespace: {{istio_namespace}}
spec:
  secretName: {{cert_secret_name}}
  commonName: "gamex.local.io"
  issuerRef:
    name: {{cert_issuer_name}}
    kind: Issuer
  dnsNames:
  - "gamex.local.io"