---
- name: preparing before starting compose
  include_tasks: pre_compose.yml

- name: starting compose
  shell: "docker-compose -p {{app_name}} -f {{staging_dir}}/docker-compose.yml up -d"

- name: post compose
  include_tasks: post_compose.yml