---
- name: create server folders
  file:
    path: "{{item}}"
    state: directory
  loop:
    "{{server_dir_collection}}"

- name: Copy compose file over
  template:
    src: docker-compose.yml
    dest: "{{staging_dir}}/docker-compose.yml"

- name: Copy server files
  template:
    src: "{{item}}"
    dest: "{{staging_dir}}/{{item}}"
  loop:
    - "server_gateway/entrypoint.sh"
    - "server_gateway/config.yml"
    - "microservices/userservice/entrypoint.sh"

- name: Include nginx conf file
  include_role:
    name: roles/add_nginx_config

- name: install backend dependencies
  shell:
    cmd: "yarn install --frozen-lockfile"
    chdir: "{{working_rest_server_dir}}"
  register: yarn_install
  failed_when: "yarn_install.rc != 0 and yarn_install.rc != 1"

- name: install frontend dependencies
  shell:
    cmd: "yarn install --frozen-lockfile"
    chdir: "{{working_frontend_dir}}"
  register: yarn_install
  failed_when: "yarn_install.rc != 0 and yarn_install.rc != 1"

- name: build frontend app
  shell:
    cmd: "yarn build"
    chdir: "{{working_frontend_dir}}"
  register: yarn_build
  failed_when: "yarn_build.rc != 0 and yarn_build.rc != 1"

