---
- name: create server folders
  file:
    path: "{{item}}"
    state: directory
  loop:
    "{{server_dir_collection}}"

- name: Copy compose file over
  template:
    src: docker-compose.yml
    dest: "{{staging_dir}}/docker-compose.yml"

- name: Copy server files
  template:
    src: "{{item}}"
    dest: "{{staging_dir}}/{{item}}"
  loop:
    - "openresty/Dockerfile"
    - "server_gateway/entrypoint.sh"
    - "server_gateway/config.yml"
    - "microservices/userservice/entrypoint.sh"

- name: "Copy nginx.conf to {{nginx_conf_dir}}"
  template:
    src: openresty/nginx.conf
    dest: "{{nginx_conf_dir}}/nginx.conf"
    mode: 0766

- name: install services npm dependencies
  shell:
    cmd: "yarn install --frozen-lockfile"
    chdir: "{{working_rest_server_dir}}"
  register: yarn_install
  failed_when: "yarn_install.rc != 0 and yarn_install.rc != 1"
