---

- hosts: localhost
  vars_files:
    - "group_vars/vault"
    - "group_vars/kuber_stage.yml"
  roles:
    - roles/kubernetes/prepare_kubernetes
  tags:
    - prepare_kubernetes

- hosts: localhost
  vars_files:
    - "group_vars/vault"
    - "group_vars/kuber_stage.yml"
  roles:
    - roles/kubernetes/install_dependencies
  tags:
    - install_dependencies

- hosts: localhost
  vars_files:
    - "group_vars/vault"
    - "group_vars/kuber_stage.yml"
  roles:
    - roles/download_artifacts
    - roles/deploy_artifacts
  tags:
    - prepare_artifacts

- hosts: localhost
  vars_files:
    - "group_vars/vault"
    - "group_vars/kuber_stage.yml"
  roles:
    - roles/kubernetes/deploy_app
  tags:
    - deploy_app