version: '3'

services:
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
        - pgadmin-datastore:/root/.pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped

volumes:
  pgadmin-datastore: