version: '3'
networks:
  gamex_gamer-camp:
    external: true
  gamex_keycloak-net:
    external: true

services:
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
        - pgadmin-datastore:/root/.pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    networks:
      - gamex_gamer-camp
      - gamex_keycloak-net

volumes:
  pgadmin-datastore: