apiVersion: v1
kind: Service
metadata:
  name: {{keycloak_service_name}}
spec:
  selector:
    app: keycloak
  ports:
  - name: 'https'
    port: {{keycloak_service_ssl_port}}
    targetPort: {{keycloak_service_ssl_port}}
  - name: 'http'
    port: {{keycloak_service_port}}
    targetPort: {{keycloak_service_port}}
