apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: redsolid/openresty-oidc
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: {{keycloak_service_port}}
        volumeMounts:
          - name: www-pv-storage
            mountPath: {{nginx_mount_path}}
          - name: config-volume
            mountPath: /usr/local/openresty/nginx/conf/nginx.conf
            subPath: nginx.conf
      volumes:
      - name: www-pv-storage
        persistentVolumeClaim:
            claimName: local-pvc
      - name: config-volume
        configMap:
          name: nginx-conf
