# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: {{kube_namespace}}
configMapGenerator:
- name: nginx-conf
  files:
  - nginx.conf
resources:
  - "service.yaml"
  - "deployment.yaml"
